# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: build

jobs:
# Please do not rename this job
  build-project:
    name: build die-beste-art
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v18.x

      - name: Build Node assets
        env:
          CI: true
          PUBLIC_CMS_API_URL: https://cms.originalfood.de/api/
          PUBLIC_CMS_URL: https://cms.originalfood.de
          PUBLIC_CONTACT_EMAIL: chocolat@die-beste.art
          PUBLIC_GITHUB_PAGE: brunosj
          PUBLIC_SHOP_URL: https://shop.originalfood.de/p/juni-degustation-entlebuch-45-schweizer-milchschokolade-2-genusstafeln-a-50-g-100-g
          PUBLIC_SITE_URL: https://die-beste.art
          SITE_URL: ${{ inputs.site-url }}
          VITE_CMS_API_URL: https://cms.originalfood.de/api/
        run: |
          npm install --global pnpm
          pnpm install
          pnpm build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: 700535f9-9d1e-413e-93d7-eac5295aacb6
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/die-beste-art/config.yaml
          action: upload
